# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches:
      - main
jobs:
  your-job-name:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.TEST_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Export API KEY
        run: export API_KEY=$TEST_API_KEY
             node deploy-script.js
